artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  dataset_url: https://drive.google.com/file/d/1RYiV0-mohCQOa5lImL1Pj3Qi8ugY44UG/view?usp=sharing
  dataset_raw: artifacts/data_ingestion/data.zip

data_validation:
  root_dir: artifacts/data_validation
  dataset_csv: artifacts/data_ingestion/stroke_data.csv
  status_file: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  dataset_csv: artifacts/data_ingestion/stroke_data.csv
